name: "Auto Manage Issue Blockers"

on:
  workflow_dispatch:

permissions:
  issues: write
  
jobs:
  call-issue-blocker:
    uses: mahati62/Workflow/.github/workflows/issue-blocker-reusuable.yml@main